# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/

#language: en
#
#pipeline:
#  - name: SpacyNLP
#    model: "en_core_web_sm"
#  - name: SpacyTokenizer
#  - name: SpacyEntityExtractor
#  - name: SpacyFeaturizer
#    pooling: mean
#  - name: CountVectorsFeaturizer
#    analyzer: char_wb
#    min_ngram: 1
#    max_ngram: 4
#  - name: DIETClassifier
#    epochs: 100
#
#policies:
#  - name: MemoizationPolicy
#  - name: RulePolicy
#  - name: TEDPolicy
#    max_history: 5
#    epochs: 100

#policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true

language: en

pipeline:
### # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
### # If you'd like to customize it, uncomment and adjust the pipeline.
### # See https://rasa.com/docs/rasa/tuning-your-model for more information.
   - name: WhitespaceTokenizer
   - name: RegexFeaturizer
   - name: RegexEntityExtractor
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: DIETClassifier
   - name: CRFEntityExtractor
     max_iterations: 100
     BILOU_flag: True
     constrain_similarities: true
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 100
     constrain_similarities: true
   - name: FallbackClassifier
     threshold: 0.3
     ambiguity_threshold: 0.1

#language: "en"
#
#pipeline:
#  - name: SpacyNLP
#  - name: SpacyTokenizer
#  - name: SpacyFeaturizer
#  - name: RegexFeaturizer
#  - name: LexicalSyntacticFeaturizer
#  - name: CountVectorsFeaturizer
#  - name: CountVectorsFeaturizer
#    analyzer: "char_wb"
#    min_ngram: 1
#    max_ngram: 4
#  - name: CRFEntityExtractor
#    epochs: 100
#  - name: EntitySynonymMapper
#  - name: ResponseSelector
#    epochs: 100


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
#policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
   - name: MemoizationPolicy
   - name: RulePolicy
   - name: TEDPolicy
     max_history: 5
     epochs: 100
     constrain_similarities: true
